language: python

matrix:
  include:
    - python: 2.7
    - python: 3.5

# start Virtual X, so default matplotlib backend works
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

# Install dependencies
install:
    pip install -r requirements.travis.txt

# command to run tests
script:
   - nosetests tests -v
