#
language: python

env:
  global:
    #- DEPENDS="cython>=0.19"
    - NO_NET=1

git:
    depth: 1000

matrix:
  include:
      - python: 3.6
        dist: xenial
        sudo: true
        services:
          - xvfb
      - python: 3.7
        dist: xenial
        sudo: true
        services:
          - xvfb
      - python: 3.8
        dist: xenial
        sudo: true
        services:
          - xvfb

# Install dependencies
install:
    - pip install -r requirements.travis.txt
    - pip install -e .
    - pip install --upgrade pip
    - pip install pytest-cov
    - pip install codacy-coverage

# command to run tests
script:
   - py.test ./tests --cov=pastas --cov-report=xml

after_success:
   - python-codacy-coverage -r coverage.xml

