#
language: python

env:
  global:
    #- DEPENDS="cython>=0.19"
    - NO_NET=1

matrix:
  include:
    - python: 2.7
    - python: 3.5

# start Virtual X, so default matplotlib backend works
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - pip install --upgrade pip
    - pip install codecov
    - pip install pytest-cov

# Install dependencies
install:
    pip install -r requirements.travis.txt

# command to run tests
script:
   - py.test --cov=pastas tests/

after_success:
   - codecov
